### ISSUE TITLE
Minimal requirements for syntax highlighting combined with ep_padwiki 

### ISSUE THREAD

**Issue by offray** [LaKing/codepad#1]
Hi,

Thanks for your work on codepad. 

I have been looking for a minimal setup that add syntax highlighting for Etherpad combined with [PadWiki](https://www.npmjs.com/package/ep_padwiki). The prototype should look like PadWiki, with a tree at the left, and pads at right, but such pads would support syntax highlighting for several languages, particularly Pandoc's Markdown with some extensions. 

I have seen that [ep_syntaxhighlighting](https://www.npmjs.com/package/ep_syntaxhighlighting) has been discontinued in favor of first versions of CodePad and the last one has been discontinued in favor of this version, but after trying to install it (with more success in the previous version that in this one) It seems that it could be overkill for the task I'm trying, described above. There is any minimal setup that I can use from this project that enables syntax highlighting in the pads of PadWiki without any of the components that support file browsing, continuous integration or the use of MongoDB?

Thanks,

**Comment by LaKing** [comment]
Hello, ..

ep_codepad used [highlightjs](https://highlightjs.org/)
bp codepad uses [codemirror](https://codemirror.net/)
.. for syntax highlighting.

Since syntax highlighting is mostly done on the browser, you can try to implant any lib around.

**Comment by LaKing** [comment]
Closing as it is not really an issue. .)

**Comment by offray** [comment]
Thanks. I'm using now [CodiMD](https://github.com/hackmdio/codimd/) that provides me with the features I was looking for.
