### ISSUE TITLE
demo not running

### ISSUE THREAD

**Issue by kernie** [LaKing/codepad#2]
Hi,

thanks for this interesting project!

I tried to start the demo site but end up with either https error message or some text:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>ERROR 503</title>
    <style type="text/css"> html, body {overflow: hidden;} </style>
  </head>
<body style="background-color:#333;">
    <div id="header" style="background-color:#222;">
        <p align="center">
            <svg xml:space="preserv
.
.
.
```
Curious to see the codepade running...

Thanks,
Maarten

**Comment by LaKing** [comment]
Sorry for the late response, I didn't see this post for some reason.

is this about the codepad demo site?

[codepad-demo.d250.hu](https://codepad-demo.d250.hu)

**Comment by kernie** [comment]
OK.
Tested the page and works.

Thanks!
